# Generated by Django 3.2.16 on 2022-12-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_categoria_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.BooleanField(default=False),
        ),
    ]
