# Generated by Django 3.2.16 on 2022-12-18 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fecha_pub',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='noticia',
            name='numero_comentarios',
            field=models.IntegerField(default=0),
        ),
    ]
