# Generated by Django 3.2.16 on 2022-12-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20221222_0410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='post',
            new_name='noticia',
        ),
    ]
